### ISSUE TITLE
[BUG]: Link refers to 404 Page

### ISSUE THREAD

**Issue by schmelto** [schmelto/schmelto#10]
![image](https://user-images.githubusercontent.com/30869493/134301220-c8311d70-49ee-4d9f-ab8f-9065c04e729e.png)

https://github.com/schmelto/schmelto/blame/main/README.md#L1

-> should be link to https://schmelto.github.io/Portfolio/

## What to do?

Change Line 1 of the README.md 
```diff
- <h1 align="center">Hi there👋, I'm <a href="https://schmelto.github.io/portfolio/">Tom</a>!</h1>
+ <h1 align="center">Hi there👋, I'm <a href="https://schmelto.github.io/Portfolio/">Tom</a>!</h1>
```

**Comment by nirban256** [comment]
Hey can I work on this issue?

**Comment by schmelto** [comment]
> Hey can I work on this issue?
> 

Sure if you need any help please let me know
